server:
  port: 8095

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 动态线程池管理配置
dynamic-thread-pool:
  registry:
    redis:
      enabled: true
      host: 127.0.0.1
      port: 6379
      password:
  notify:
    enabled: true
    usePlatform:
      - DingDing
      - FeiShu
    accessToken:
      dingDing:
      feiShu:
    secret:
      dingDing:
      feiShu:
  report:
    cron: "*/20 * * * * ?"


redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml