server:
  port: 8089

app:
  config:
    api-version: v1
    cross-origin: "*"
    username: admin
    password: admin
    grafanaUrl: localhost:3000

jwt:
  secret:
  expiration: 259200

redis:
  sdk:
    config:
      host: localhost
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml