version: "3"
services:
  dynamic-tp-admin:
    container_name: dynamic-tp-admin
    image: registry.cn-heyuan.aliyuncs.com/coding_01/dynamic-thread-pool-admin:1.3
    ports:
      - "8089:8089"
    environment:
      CROSS_ORIGIN: "http://dtp.kangyaocoding.top"
      REDIS_HOST: 172.18.0.5
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      JWT_SECRET:
      JWT_EXPIRATION: 259200
      ADMIN_USERNAME:
      ADMIN_PASSWORD:
      GRAFANA_URL: http://172.18.0.7:4000/d/cdvvy9felux34e/e58aa8-e68081-e7babf-e7a88b-e6b1a0-e79b91-e68ea7?orgId=2&refresh=5s&theme=light
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
